name: DevOps-GitHubActions
on: push
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: List Files for Debugging
        run: |
          echo "Listing files in the current directory:"
          ls -R
          echo "Listing files in ./dist:"
          ls -R ./dist || echo "./dist directory does not exist"
      - name: Upload artifact to enable deployment
        if: success()  # Only run if the previous steps succeed
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist # Pastikan ini mengarah ke direktori build Anda
